last_change = 2026-08-14T15:52:10.037410Z
addr = 0x9d8fc0
size = 0x68
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
type = "long long"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0x9d8fc0
type = "long long"

[header.args]
