last_change = 2026-08-14T15:52:10.037415Z
addr = 0x9eaf00
size = 0x9e2
name = "CLoopModeGame_RegisterEventMapInternal"
type = "long long"

[header]
name = "CLoopModeGame_RegisterEventMapInternal"
addr = 0x9eaf00
type = "long long"

[header.args]
