last_change = 2026-08-14T15:52:10.037485Z
addr = 0xb1c330
size = 0x175
name = "CSource2Client_OnDisconnect"
type = "double"

[header]
name = "CSource2Client_OnDisconnect"
addr = 0xb1c330
type = "double"

[header.args]
