last_change = 2026-08-14T15:52:10.037503Z
addr = 0xb84bc0
size = 0xe8c
name = "CPrediction_PostNetworkDataReceived"
type = "long long"

[header]
name = "CPrediction_PostNetworkDataReceived"
addr = 0xb84bc0
type = "long long"

[header.args]
