last_change = 2026-08-14T15:52:10.037532Z
addr = 0xf02d90
size = 0x9f
name = "GameStateAPI_GetAssociatedTeamNumber"
type = "long long"

[header]
name = "GameStateAPI_GetAssociatedTeamNumber"
addr = 0xf02d90
type = "long long"

[header.args]
