last_change = 2026-08-14T15:52:10.037545Z
addr = 0xf05f80
size = 0xa6
name = "GameStateAPI_GetCrosshairCode"
type = "char *"

[header]
name = "GameStateAPI_GetCrosshairCode"
addr = 0xf05f80
type = "char *"

[header.args]
