last_change = 2026-08-14T15:52:10.037737Z
addr = 0xf5d830
size = 0x5e
name = "GameStateAPI_ShouldShowHudElements"
type = "bool"

[header]
name = "GameStateAPI_ShouldShowHudElements"
addr = 0xf5d830
type = "bool"

[header.args]
