last_change = 2026-08-14T15:52:10.037750Z
addr = 0x14e7f50
size = 0x4d9
name = "CEntitySystem_ctor"
type = "long long"

[header]
name = "CEntitySystem_ctor"
addr = 0x14e7f50
type = "long long"

[header.args]
